import type { ShaderDef, UniformMap } from '../types'
import { buildFragment, buildVertex } from '../shaders/build'

export type ExportTarget = 'glsl-frag' | 'glsl-vert' | 'threejs' | 'r3f' | 'uniforms-json'

export const EXPORT_TARGETS: { id: ExportTarget; label: string; lang: string }[] = [
  { id: 'glsl-frag', label: 'Fragment (GLSL)', lang: 'glsl' },
  { id: 'glsl-vert', label: 'Vertex (GLSL)', lang: 'glsl' },
  { id: 'threejs', label: 'Three.js ShaderMaterial', lang: 'javascript' },
  { id: 'r3f', label: 'React Three Fiber', lang: 'javascript' },
  { id: 'uniforms-json', label: 'Uniforms JSON', lang: 'json' },
]

function jsUniformInit(uniforms: UniformMap): string {
  const lines = [
    'uTime: { value: 0 },',
    'uResolution: { value: [1, 1] },',
    'uMouse: { value: [0.5, 0.5] },',
  ]
  for (const [name, u] of Object.entries(uniforms)) {
    if (u.type === 'color') lines.push(`${name}: { value: [${u.value.join(', ')}] }, // ${u.label}`)
    else if (u.type === 'vec2') lines.push(`${name}: { value: [${u.value.join(', ')}] }, // ${u.label}`)
    else if (u.type === 'bool') lines.push(`${name}: { value: ${u.value} }, // ${u.label}`)
    else lines.push(`${name}: { value: ${u.value} }, // ${u.label}`)
  }
  return lines.map((l) => '    ' + l).join('\n')
}

export function generateExport(def: ShaderDef, target: ExportTarget): string {
  // embed current parameter values as comments so exported GLSL reflects live edits
  const frag = buildFragment(def, true)
  const vert = buildVertex(def, true)
  const is3D = def.kind === 'vertex' || def.kind === 'material'
  // a mesh that actually shows the effect: a sphere for 3D shaders, a quad otherwise
  const geometryJsx = is3D
    ? '<icosahedronGeometry args={[1.2, 64]} />'
    : '<planeGeometry args={[2, 2]} />'
  switch (target) {
    case 'glsl-frag':
      return frag
    case 'glsl-vert':
      return vert
    case 'uniforms-json': {
      const obj: Record<string, unknown> = {}
      for (const [name, u] of Object.entries(def.uniforms)) obj[name] = u.value
      return JSON.stringify({ id: def.id, name: def.name, uniforms: obj }, null, 2)
    }
    case 'threejs':
      return `import * as THREE from 'three'

// "${def.name}" — generated by Shader Studio
const vertexShader = \`${vert}\`

const fragmentShader = \`${frag}\`

export function create${pascal(def.id)}Material() {
  return new THREE.ShaderMaterial({
    uniforms: {
${jsUniformInit(def.uniforms)}
    },
    vertexShader,
    fragmentShader,
  })
}

// In your render loop:
//   material.uniforms.uTime.value = clock.getElapsedTime()
`
    case 'r3f':
      return `import { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

// "${def.name}" — generated by Shader Studio
const vertexShader = \`${vert}\`
const fragmentShader = \`${frag}\`

const uniforms = {
${jsUniformInit(def.uniforms)}
}

export function ${pascal(def.id)}({ ...props }) {
  const ref = useRef<THREE.ShaderMaterial>(null!)
  useFrame((state) => {
    ref.current.uniforms.uTime.value = state.clock.elapsedTime
  })
  return (
    <mesh {...props}>
      ${geometryJsx}
      <shaderMaterial
        ref={ref}
        uniforms={uniforms}
        vertexShader={vertexShader}
        fragmentShader={fragmentShader}
      />
    </mesh>
  )
}
`
  }
}

function pascal(id: string): string {
  return id
    .split(/[-_]/)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('')
}
